// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go/go-backend-api/internal/controller"
	"go/go-backend-api/internal/repo"
	"go/go-backend-api/internal/service"
)

// Injectors from pong.wire.go:

func InitPongHandler(id int) (*controller.PongController, error) {
	iPongRepo := repo.NewPongRepo(id)
	iPongService := service.NewPongService(iPongRepo)
	pongController := controller.NewPongController(iPongService)
	return pongController, nil
}
