server:
  port: 8081
  profile: ""

mysql:
  host: 127.0.0.1
  port: 3306
  username: dev
  password: dev123
  dbname: godbdev
  maxIdleCons: 10
  maxOpenCons: 100
  connMaxLifeTime: 3600
  autoCreate: true

logger:
  level: info
  filename: "./storages/logs/app.log"
  maxSize: 10
  maxBackups: 3
  maxAge: 28
  compress: true

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  poolSize: 10
  maxActiveConns: 0
  maxIdleConns: 0

smtp:
  host: smtp.gmail.com
  port: 587
  username: xxxxxxxxxxx@gmail.com
  password: "xxxx xxxx xxxx xxxx"