server:
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  username: dev
  password: dev123
  dbname: godbdev
  maxIdleCons: 10
  maxOpenCons: 100
  connMaxLifeTime: 3600
  autoCreate: true

logger:
  level: info
  filename: "./storages/logs/app.log"
  maxSize: 10
  maxBackups: 3
  maxAge: 28
  compress: true