services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    #environment:
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,CONTROLLER://127.0.0.1:9093  # Use the container name or routable address
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # KAFKA_PROCESS_ROLES: broker,controller
      # KAFKA_NODE_ID: 1
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # KAFKA_LOG_DIRS: /tmp/kafka-logs
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      #- "127.0.0.1:9092:9092"
      - "9092:9092"
    networks:
      - kafka-network

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local-cluster
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092  # Use 'kafka' as the hostname to resolve to the Kafka container
  #   ports:
  #     - "9091:8080"
  #   networks:
  #     - kafka-network

networks:
  kafka-network:
    driver: bridge
